SELECT
A.AUTHOR_ID AS AUTHOR_ID
,A.AUTHOR_NAME AS AUTHOR_NAME
,B.CATEGORY AS CATEGORY
,SUM(SALES*PRICE) AS TOTAL_SALES

FROM BOOK B , AUTHOR A, BOOK_SALES S
WHERE B.AUTHOR_ID = A.AUTHOR_ID
AND B.BOOK_ID = S.BOOK_ID
AND DATE_FORMAT(S.SALES_DATE, '%Y-%m')  = '2022-01'

GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;