SELECT
U.USER_ID AS USER_ID,
U.NICKNAME AS NICKNAME,
SUM(PRICE) AS TOTAL_SALES

FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
AND B.STATUS = 'DONE'

GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000

ORDER BY TOTAL_SALES;
